 processor:
    build:
      context: .
      dockerfile: docker/Processor.Dockerfile
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - processor_data:/app/data
    networks:
      - jewelry-net