# kubernetes/services/scraper-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: jewelry-scraper
  labels:
    app: jewelry-scraper
spec:
  selector:
    app: jewelry-scraper
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
